### ISSUE TITLE
fix broken cloud build job for nfs driver

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-driver-nfs#94] opened 2020-11-17 02:31 UTC
**What happened**:

fyi, we disabled the cloud build job for nfs because it has never passed:
https://github.com/kubernetes/test-infra/pull/19937/files#diff-6572b562b74e036959cc413b3e4b7eb275f82e89218a1b1eb36a3dfb136348cdR39

https://k8s-testgrid.appspot.com/sig-storage-image-build#post-csi-driver-nfs-push-images

Can you help fix the job?

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mayankshah1607** [comment] 2020-11-17 06:06
I think this may be a duplicate of https://github.com/kubernetes-csi/csi-driver-nfs/issues/67

**Closed** 2020-11-26 01:18 UTC
Labels: kind/bug
